# Generated by Django 4.2.4 on 2023-08-24 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Dough', 'Dough'), ('Spicery', 'Spicery'), ('Sauce', 'Sauce'), ('Meat_products', 'Meat products'), ('Cheese', 'Cheese')], default='Dough', max_length=20)),
                ('time', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredient',
            },
        ),
    ]
