# Generated by Django 4.2.4 on 2023-08-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingridients', '0002_alter_ingredients_options_alter_ingredients_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
